permalink: '/blog/:year/:month/:title.html'
navigation:
    - {title: 'Soutěže', category: 'souteze', url: '/souteze/index.html'}
    - {title: 'Koučování', category: 'koucovani', url: '/koucovani/index.html'}
    - {title: 'Blog', category: 'blog', url: '/blog/index.html'}
